:GitHub Actions Workflow Dosyası:.github/workflows/release-builder.yml
# Python EXE dosyası oluşturmak için GitHub Actions iş akışı
name: Python Release EXE Builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Depoyu Dışarı Çek
      uses: actions/checkout@v4

    - name: Python'ı Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Bağımlılıkları Kur
      working-directory: ./allone
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # PyInstaller komutu, backend_logic modülünü açıkça dahil edecek şekilde güncellendi
    - name: PyInstaller ile Uygulama Oluştur
      working-directory: ./allone
      run: |
        pyinstaller --onefile --windowed --name="AllOneTool" --icon="icon.ico" --hidden-import="backend_logic" main.py

    # Yeni GitHub Release'i oluştur ve .exe'yi yükle
    - name: GitHub Release Oluştur ve EXE Dosyasını Yükle
      uses: softprops/action-gh-release@v2
      with:
        files: allone/dist/AllOneTool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


Bu değişikliği yaptıktan sonra, yeni bir etiket (`v3.3.6` gibi) ekleyerek GitHub'da yeni bir release oluşturun. Bu yeni `.exe` dosyası, `backend_logic` modülünü doğru bir şekilde içerecek ve uygulamanızın tekrar çalışmasını sağlayacaktır.
