# NİHAİ ÜRETİM SÜRÜMÜ
name: Python Release EXE Builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./allone
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Adım 4: PyInstaller komutu son kullanıcı için düzenlendi
    - name: Build executable with PyInstaller
      working-directory: ./allone
      run: |
        pyinstaller --onefile --windowed --name="AllOneTool" --icon="icon.ico" --hidden-import="numpy" main.py

    # Adım 5: Yeni GitHub Release'i oluştur ve .exe'yi yükle
    - name: Create GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: allone/dist/AllOneTool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
