# Bu dosyanın tam yolu: .github/workflows/release-builder.yml olmalı
name: Python Release EXE Builder

# Bu otomasyon ne zaman çalışacak?
# main branch'e v ile başlayan bir "tag" gönderildiğinde (örn: v2.9.1)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    # Hangi sanal makinede çalışacak? Windows .exe'si için Windows olmalı.
    runs-on: windows-latest

    steps:
    # Adım 1: Proje kodunu sanal makineye indir
    - name: Checkout repository
      uses: actions/checkout@v3

    # Adım 2: Python'u kur
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Kullandığınız Python versiyonuna yakın bir versiyon

    # Adım 3: Gerekli kütüphaneleri yükle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r allone/requirements.txt
        pip install pyinstaller

    # Adım 4: PyInstaller ile .exe dosyasını oluştur
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name="AllOneTool" --icon="allone/icon.ico" allone/main.py
      # NOT: icon.ico dosyanızın allone/ klasörü içinde olduğundan emin olun!

    # Adım 5: Yeni GitHub Release'i oluştur ve .exe'yi yükle
    - name: Create GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v1
      with:
        # Bu, 'dist' klasörünün içindeki .exe dosyasını bulup yükler
        files: dist/AllOneTool.exe
        # Release'in adını ve notlarını otomatik olarak tag'den alır
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
