# HATA AYIKLAMA İÇİN DÜZENLENMİŞ SÜRÜM
name: Python Release EXE Builder (Debug Mode)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./allone
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Adım 4: PyInstaller komutundan --windowed kaldırıldı ve isim değiştirildi
    - name: Build executable with PyInstaller for Debugging
      working-directory: ./allone
      run: |
        pyinstaller --onefile --name="AllOneTool_Debug" --icon="icon.ico" --hidden-import="numpy" main.py

    # Adım 5: Yeni GitHub Release'i oluştur ve debug .exe'yi yükle
    - name: Create GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: allone/dist/AllOneTool_Debug.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
